tools: Add support for native arch builds

diff --git a/u-boot/tools/build b/u-boot/tools/build
--- a/u-boot/tools/build
+++ b/u-boot/tools/build
@@ -17,18 +17,28 @@ CROSS_TOOL_PREFIX=""
 if [ "$TARGET_ARCH" == "arm64" ]; then
 	TOOLCHAIN_ARCH=aarch64
 fi
-for i in unknown-haiku none-eabi linux-gnu; do
-	if [ -x "$(command -v $TOOLCHAIN_ARCH-$i-ld)" ]; then
-		echo "Found $i cross compiler!"
-		CROSS_TOOL_PREFIX=$TOOLCHAIN_ARCH-$i
-		break;
+if [ $(uname -m) == $TOOLCHAIN_ARCH ]; then
+	echo "Native architecture build"
+	CROSS_TOOL_PREFIX=""
+	if ! [ -x "$(command -v ld)" ]; then
+		echo "Error: development tools not installed!"
+		exit 1
 	fi
-done
-
-if ! [ -n "$CROSS_TOOL_PREFIX" ]; then
-	echo "Error: Unable to locate compatible cross-compiler in PATH!"
-	exit 1
+else
+	echo "Cross compile build"
+	for i in unknown-haiku none-eabi linux-gnu elf; do
+		if [ -x "$(command -v $TOOLCHAIN_ARCH-$i-ld)" ]; then
+			echo "Found $i cross compiler!"
+			CROSS_TOOL_PREFIX=$TOOLCHAIN_ARCH-$i-
+			break;
+		fi
+	done
+	if ! [ -n "$CROSS_TOOL_PREFIX" ]; then
+		echo "Error: Unable to locate compatible cross-compiler in PATH!"
+		exit 1
+	fi
 fi
+
 
 if ! [ -d "$TARGET_ARCH" ]; then
 	echo "Error: Unable to locate ./$TARGET_ARCH directory!"
@@ -71,7 +81,7 @@ for dir in $WORK_QUEUE; do
 		echo "Error configuring $dir"
 		continue;
 	fi
-	ARCH=$TARGET_ARCH CROSS_COMPILE=$CROSS_TOOL_PREFIX- make -C $TMP -j2
+	ARCH=$TARGET_ARCH CROSS_COMPILE=$CROSS_TOOL_PREFIX make -C $TMP -j2
 	if [ $? -ne 0 ]; then
 		echo "Error building $dir"
 		continue;
@@ -96,5 +106,5 @@ for dir in $WORK_QUEUE; do
 	sed -i "s^%%FILES%%^$FILES^g" $dir/README.md
 	sed -i "s^%%CONFIG%%^$CONFIG^g" $dir/README.md
 	sed -i "s^%%TARGET_ARCH%%^$TARGET_ARCH^g" $dir/README.md
-	sed -i "s^%%CROSS_TOOL%%^$CROSS_TOOL_PREFIX^g" $dir/README.md
+	sed -i "s^%%CROSS_TOOL%%^$CROSS_TOOL_PREFIX-^g" $dir/README.md
 done
